keywords:
- devops
- dev
- azure
- azure devops
- terraform
- kubernetes
- k8s
- cloud
- pulumi
- aws
- s3
- infrastructure
- infrastructure as code
- ci/cd
- cicd
- continuous integration
- continuous delivery
- security
- zerotrust
- zero trust
- devopssec
- powershell
- pwsh
- python
- docker
- large language model
- llm
- ai
- ml
- gemini
- vscode
- copilot
- github copilot
- artificial intelligence
- machine learning
- dotnet
rss:
- https://habr.com/ru/rss/articles/?fl=en
- https://news.ycombinator.com/rss
- https://dev.to/feed
- https://thenewstack.io/feed/
- https://www.darkreading.com/rss.xml
- https://www.bleepingcomputer.com/feed/
- https://feeds.feedburner.com/Securityweek
- https://cloudnativenow.com/feed/
